# Generated by Django 5.2.3 on 2025-06-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installed_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'Request'), ('maintenance', 'Maintenance'), ('yearly', 'Yearly'), ('none', 'None')], default='none', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installed_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='installed_devices.installeddevice')),
            ],
        ),
    ]
