# Generated by Django 5.2.3 on 2025-06-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('installation_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_devices', to='customers.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_devices', to='devices.device')),
            ],
        ),
    ]
